name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: TestCalculator.time
      id: testcalculator-time
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: TestCalculator.time
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "CalculatorTest.testTime"
        timeout: 10
        max-score: 4
    - name: TestCalculator.divide
      id: testcalculator-divide
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: TestCalculator.divide
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "CalculatorTest.testDivide"
        timeout: 10
        max-score: 4
    - name: TestCalculator.divideZero
      id: testcalculator-dividezero
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: TestCalculator.divideZero
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "CalculatorTest.testDivideZero"
        timeout: 10
        max-score: 4
    - name: TestMain
      id: testmain
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: TestMain
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog61Test.testMain"
        timeout: 10
        max-score: 4
    - name: TestPrintedMessage
      id: testprintedmessage
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: TestPrintedMessage
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog61Test.testPrintedMessage"
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTCALCULATOR-TIME_RESULTS: "${{steps.testcalculator-time.outputs.result}}"
        TESTCALCULATOR-DIVIDE_RESULTS: "${{steps.testcalculator-divide.outputs.result}}"
        TESTCALCULATOR-DIVIDEZERO_RESULTS: "${{steps.testcalculator-dividezero.outputs.result}}"
        TESTMAIN_RESULTS: "${{steps.testmain.outputs.result}}"
        TESTPRINTEDMESSAGE_RESULTS: "${{steps.testprintedmessage.outputs.result}}"
      with:
        runners: testcalculator-time,testcalculator-divide,testcalculator-dividezero,testmain,testprintedmessage
